name: Update Search Index

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'resolution'
  
  workflow_dispatch:

defaults:
  run:
    working-directory: ${{ github.workspace }}

jobs:
  update-index:
    runs-on: self-hosted
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python virtual environment
        run: |
          uv venv

        # Use UV since it's really fast at downloading packages and setting up enviroments

      - name: Install dependencies
        run: |
          uv pip install pyyaml

        # PyYAML is the only dependency needed to run the search index generator. Also, no need to source the venv, UV handles that automatically for both running and installing.

      - name: Generate search index
        run: |
          uv run generate_searchindex.py
      
      - name: Check for changes
        run: git diff --exit-code -- searchindex.csv || echo "changed=true" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}
      
      - name: Commit and push if changed
        if: success() && steps.git-check.outputs.changed == 'true'
        working-directory: ${{ github.workspace }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add searchindex.csv
          git commit -m "Update search index"
          git push

