name: Update Search Index

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'resolution'
  
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  update-index:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo   # <--- fix

      - name: Set up Python virtual environment
        working-directory: repo
        run: uv venv

      - name: Install dependencies
        working-directory: repo
        run: uv pip install pyyaml

      - name: Generate search index
        working-directory: repo
        run: uv run generate_searchindex.py

      - name: Check for changes
        id: git-check
        working-directory: repo
        run: |
          git diff --exit-code -- searchindex.csv || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        working-directory: repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add searchindex.csv
          git commit -m "Update search index"
          git push
