name: Update Package Hashes

permissions:
  contents: write

concurrency:
  group: package-chores
  cancel-in-progress: false

on:
  push:
    paths:
      - "packages/**/src/**" # Only trigger on changes in package source files
  
  workflow_dispatch:

jobs:
  update-hash:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update hashes
        run: |
          cd packages
          python hasher.py
          cd ..

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code -- packages/ || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add packages/
          git commit -m "chore: recreate hashes to keep up to date"
          git push
